"""契约测试：workpacket

⚠️ 本文件由 `python scripts/gen_contract_tests.py` 生成。【不要手改】—— 下次生成会覆盖。

测的不是「我们的固件对不对」（那是 validate_fixtures 的事），
而是【任何实现都必须满足的契约行为】：合法的必须过，非法的必须拒。

★ 反例由真实固件变异而来，不是凭空造的 ——
  凭空造的实例容易在别处就不合法，于是测试通过的原因与它想测的东西无关。

★ 每条用例都走两条校验路径，两条都必须一致地判定：
    schema 层  scripts/lib/schema.py（零依赖）
    模型层     codentum_contracts.WorkPacket（Pydantic 运行时校验）
  两者不一致 = 生成器与 schema 之间出现了缝，而那是跨语言漂移的入口。

跑：pytest tests/contract

真源：packages/contracts/schemas/workpacket.schema.json
生成器：scripts/gen_contract_tests.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "packages" / "contracts" / "python"))

from codentum_contracts import WorkPacket  # noqa: E402
from lib.schema import load_schemas, validate  # noqa: E402

SCHEMA_FILE = "workpacket.schema.json"
_SCHEMAS = load_schemas(ROOT / "packages" / "contracts" / "schemas")


def check_schema(v: object) -> list[str]:
    return validate(_SCHEMAS[SCHEMA_FILE], v, _SCHEMAS, SCHEMA_FILE)


def check_model(v: object) -> list[str]:
    try:
        WorkPacket.model_validate(v)
    except Exception as e:  # noqa: BLE001
        return [str(e)]
    return []

# ══════════════════════════════════════════════════════════
#  正例：10 份真实固件必须全部通过
# ══════════════════════════════════════════════════════════

POSITIVES = [
    ("blocked/packets/wp-a1c001.json", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("blocked/packets/wp-b2d002.json", {"id": "wp-b2d002", "kind": "impl", "state": "blocked", "role": "coder", "ownsPaths": ["src/auth/"], "readsPaths": ["packages/contracts/", "tests/", "src/api/types.ts"], "deps": ["wp-a1c001"], "acceptance": {"kind": "test", "predicate": "pnpm vitest run tests/auth --reporter=json", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 2.5, "spentCny": 2.5, "degradationChain": ["drop_semantic_memory", "summarize_history"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 3, "evidence": ["ev-011", "ev-012", "ev-013"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:12:00.000Z", "parent": "wp-a1c001"}}),
    ("blocked/packets/wp-c3e003.json", {"id": "wp-c3e003", "kind": "review", "state": "running", "role": "reviewer", "ownsPaths": ["src/api/"], "readsPaths": ["packages/contracts/", "tests/"], "deps": ["wp-a1c001"], "acceptance": {"kind": "test", "predicate": "pnpm vitest run tests/api --reporter=json", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 2.05, "degradationChain": ["drop_semantic_memory", "shrink_review_context"]}, "routing": {"model": "claude-sonnet-5", "effort": "high"}, "attempts": 1, "evidence": [], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:12:00.000Z", "parent": "wp-a1c001"}}),
    ("blocked/packets/wp-d4f004.json", {"id": "wp-d4f004", "kind": "impl", "state": "running", "role": "coder", "ownsPaths": ["src/web/"], "readsPaths": ["packages/contracts/", "tests/"], "deps": ["wp-a1c001"], "acceptance": {"kind": "test", "predicate": "pnpm vitest run tests/web --reporter=json", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 1.94, "degradationChain": ["drop_semantic_memory", "summarize_history"]}, "routing": {"model": "claude-sonnet-5", "effort": "medium"}, "attempts": 1, "evidence": [], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:12:00.000Z", "parent": "wp-a1c001"}}),
    ("blocked/packets/wp-f6h006.json", {"id": "wp-f6h006", "kind": "fix", "state": "pending", "role": "coder", "ownsPaths": ["src/auth/session.ts"], "readsPaths": ["packages/contracts/", "tests/"], "deps": ["wp-b2d002"], "acceptance": {"kind": "manual", "predicate": "operator_approval:contract_adjacent_change", "authoredBy": "architect"}, "budget": {"currency": "CNY", "limitCny": 1.5, "spentCny": 0, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 0, "evidence": [], "provenance": {"createdBy": "helper", "createdAt": "2026-08-02T10:47:30.000Z", "parent": "wp-b2d002"}}),
    ("mid-flight/packets/wp-a1c001.json", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("mid-flight/packets/wp-b2d002.json", {"id": "wp-b2d002", "kind": "impl", "state": "running", "role": "coder", "ownsPaths": ["src/auth/"], "readsPaths": ["packages/contracts/", "tests/", "src/api/types.ts"], "deps": ["wp-a1c001"], "acceptance": {"kind": "test", "predicate": "pnpm vitest run tests/auth --reporter=json", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 2.5, "spentCny": 1.08, "degradationChain": ["drop_semantic_memory", "summarize_history"]}, "routing": {"model": "claude-opus-5", "effort": "medium"}, "attempts": 1, "evidence": [], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:12:00.000Z", "parent": "wp-a1c001"}}),
    ("mid-flight/packets/wp-c3e003.json", {"id": "wp-c3e003", "kind": "impl", "state": "running", "role": "coder", "ownsPaths": ["src/api/"], "readsPaths": ["packages/contracts/", "tests/"], "deps": ["wp-a1c001"], "acceptance": {"kind": "test", "predicate": "pnpm vitest run tests/api --reporter=json", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 1.31, "degradationChain": ["drop_semantic_memory", "summarize_history"]}, "routing": {"model": "claude-opus-5", "effort": "medium"}, "attempts": 2, "evidence": [], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:12:00.000Z", "parent": "wp-a1c001"}}),
    ("mid-flight/packets/wp-d4f004.json", {"id": "wp-d4f004", "kind": "impl", "state": "running", "role": "coder", "ownsPaths": ["src/web/"], "readsPaths": ["packages/contracts/", "tests/"], "deps": ["wp-a1c001"], "acceptance": {"kind": "test", "predicate": "pnpm vitest run tests/web --reporter=json", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.35, "degradationChain": ["drop_semantic_memory", "summarize_history"]}, "routing": {"model": "claude-sonnet-5", "effort": "medium"}, "attempts": 1, "evidence": [], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:12:00.000Z", "parent": "wp-a1c001"}}),
    ("mid-flight/packets/wp-e5g005.json", {"id": "wp-e5g005", "kind": "integrate", "state": "pending", "role": "integrator", "ownsPaths": ["src/"], "readsPaths": ["packages/contracts/", "tests/"], "deps": ["wp-b2d002", "wp-c3e003", "wp-d4f004"], "acceptance": {"kind": "test", "predicate": "pnpm vitest run tests/e2e --reporter=json", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 2, "spentCny": 0, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 0, "evidence": [], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:12:00.000Z"}}),
]


@pytest.mark.parametrize(("fixture_id", "value"), POSITIVES, ids=[p[0] for p in POSITIVES])
def test_positive(fixture_id: str, value: object) -> None:
    assert check_schema(value) == [], f"合法固件不应报错：{fixture_id}"
    assert check_model(value) == [], f"Pydantic 模型拒绝了合法固件：{fixture_id}"

# ══════════════════════════════════════════════════════════
#  反例：31 种变异必须【全部被拒】
#
#  ★ 这些不是"边界情况"，是契约的定义本身。
#    任何一条变成绿灯，都说明校验器漏了一处，
#    而漏掉的那处正是 Agent 最可能踩的地方。
# ══════════════════════════════════════════════════════════

NEGATIVES = [
    ("删掉必填字段 id", {"kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 kind", {"id": "wp-a1c001", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 state", {"id": "wp-a1c001", "kind": "contract", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 role", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 ownsPaths", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 readsPaths", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 deps", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 acceptance", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 budget", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 attempts", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 evidence", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 provenance", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"]}),
    ("删掉必填字段 acceptance.kind", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 acceptance.predicate", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 acceptance.authoredBy", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 budget.currency", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 budget.limitCny", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 budget.spentCny", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 budget.degradationChain", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 routing.model", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 routing.effort", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 provenance.createdBy", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("删掉必填字段 provenance.createdAt", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner"}}),
    ("枚举字段 kind 填非法值", {"id": "wp-a1c001", "kind": "__不是合法枚举值__", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("枚举字段 state 填非法值", {"id": "wp-a1c001", "kind": "contract", "state": "__不是合法枚举值__", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("枚举字段 role 填非法值", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "__不是合法枚举值__", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("枚举字段 acceptance.kind 填非法值", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "__不是合法枚举值__", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("枚举字段 acceptance.authoredBy 填非法值", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "__不是合法枚举值__"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("枚举字段 routing.effort 填非法值", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "__不是合法枚举值__"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("枚举字段 provenance.createdBy 填非法值", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "__不是合法枚举值__", "createdAt": "2026-08-02T09:02:00.000Z"}}),
    ("加一个未声明的字段（additionalProperties: false）", {"id": "wp-a1c001", "kind": "contract", "state": "accepted", "role": "architect", "ownsPaths": ["packages/contracts/"], "readsPaths": ["docs/"], "deps": [], "acceptance": {"kind": "schema", "predicate": "pnpm gen:check && pnpm typecheck", "authoredBy": "qa"}, "budget": {"currency": "CNY", "limitCny": 3, "spentCny": 0.91, "degradationChain": ["drop_semantic_memory"]}, "routing": {"model": "claude-opus-5", "effort": "high"}, "attempts": 1, "evidence": ["ev-001"], "provenance": {"createdBy": "planner", "createdAt": "2026-08-02T09:02:00.000Z"}, "__未声明的字段__": 1}),
]


@pytest.mark.parametrize(("why", "value"), NEGATIVES, ids=[n[0] for n in NEGATIVES])
def test_negative(why: str, value: object) -> None:
    assert check_schema(value) != [], f"这份数据违反契约，schema 校验却放行了：{why}"
    assert check_model(value) != [], f"这份数据违反契约，Pydantic 模型却放行了：{why}"
